### ISSUE TITLE
Make `makinde` a contributor :)

### ISSUE THREAD

**Issue by makinde** [352Media/mongoose-authorization#21]
Can I be a contributor to the project? It'd be nice to be able to create milestones and assign tasks to projects.

**Comment by makinde** [comment]
Also, FYI @xChrisPx @brysgo, I'm about to have to switch back to doing a lot more work on my core project, so it'd be awesome have your help finishing out the TODO's and writing unit tests. I'm happy to keep chiming in on design decisions.

**Comment by brysgo** [comment]
@makinde - sounds good, I don't have a ton of time to dedicate to this, but I'll give what I can.

**Comment by chrismatix** [comment]
@makinde same as @brysgo, but I will do my best. I am not authorized to do so however @dvideby0 is. Good occasion to say thank you for all the time and initiative you have put in this so far!

**Comment by makinde** [comment]
FYI @xChrisPx and @brysgo , I just published my fork to npm. Feel free to submit PR's against `devcolor/mongoose-authz`, or install it for your use.

**Comment by chrismatix** [comment]
Great! By the way I just published the latest version on dev as **2.0.0-alpha.1**
