### ISSUE TITLE
Add Option to Make AuthLevel Flag Required

### ISSUE THREAD

**Issue by makinde** [352Media/mongoose-authorization#5]
I'm considering using the library to control access to my models across the board. To make sure it is used around the codebase, I'd like to configure a setting on the schema that forces callers to have an authLevel. If it isn't present, it should throw an exception or just not return any data for reads. For writes it could do what it does now when you aren't authorized to save/remove the doc.

**Comment by chrismatix** [comment]
Hi, @makinde can you give me an example for how you'd like the API to look?

**Comment by makinde** [comment]
Happy to. I think [plugin options](http://mongoosejs.com/docs/plugins.html) would be a good fit here. Something like:

```
mySchema.plugin(mongooseAuthorization, { required: true });
```

In the future I could imagine having a dictionary that contained actions that had authorization required, but that doesn't seem necessary at this point (at least for my use case). Just highlighting this as a similar pattern that [mongoose-lean-virtuals](https://www.npmjs.com/package/mongoose-lean-virtuals) uses.
```
mySchema.plugin(mongooseAuthorization, { required: ['read', 'save'] });
```
