### ISSUE TITLE
Support paths into nested objects

### ISSUE THREAD

**Issue by makinde** [352Media/mongoose-authorization#8]
line 31 in `lib/helpers.js` is this `.filter(path => schema.path(path) || schema.virtualpath(path)) // ensure fields are in schema`

That line causes nested paths not to work. Here are the test cases that fail: https://github.com/brysgo/mongoose-authorization/commit/aeca41cc8896653a903edc393dd582c155f8b95d

**Comment by makinde** [comment]
@brysgo, could you rebase your branch to my latest commits?

Also, I hadn't built out cases for this yet. The latest code support putting a permissions object (and also a `getAuthLevel` method) into sub-schemas and having that checked when the parent schema is checked. I didn't handle the case for inline child objects in the schema file. What's the behavior you expect at the top level of the library? Are you wanting to be able to allow permissions for `nested.thing` but not for `nested.foo`?

**Comment by brysgo** [comment]
no, when I try and do nested objects

I need to have the sub object, so I add `nested.foo` and `nested.thing`

However, I get an error that I don't have access to `nested`, so I add `nested` and it gets filtered out as not being in the schema.

**Comment by makinde** [comment]
When you have `nested` in the list of accessible fields, shouldn't the whole object come back without having to specify the sub-keys?

**Comment by makinde** [comment]
I think I'm missing the point. Could you write a unit test in `index.tests.js` so I can see what you're trying to do at the level of the query?

**Comment by brysgo** [comment]
Sure, I will also rebase my stuff when I get a chance.

**Comment by brysgo** [comment]
~~did you ever see this? https://github.com/devcolor/mongoose-authorization/pull/1/files~~

EDIT: just answered my own question since you were using the same field names I used in convo

**Comment by makinde** [comment]
Oh, I think I see what you're saying. This is gonna take a bit of digging. We could just get rid of that line, but it feels so good to know that the function in question will only return valid paths and the rest of the code doesn't need to keep checking if the authorizedFields are actually in the schema.

I've gotta go out right now, but should be able to think about this some more tonight. I'm not too familiar with our mongoose handles nested inline documents.

**Comment by makinde** [comment]
@brysgo See above commit. I've fixed this (at least for find queries)

**Comment by brysgo** [comment]
@makinde awesome, I will rebase and check it out.
