### ISSUE TITLE
How should the library behave when `Model.update()` is called without an authLevel?

### ISSUE THREAD

**Issue by makinde** [352Media/mongoose-authorization#9]
For update queries, there is no document to pass to a `getAuthLevel` method.

Should the library enforce the for updates, an `authLevel` must be set, and throw a permission denied if not? Or should it call `getAuthLevel` without a document and force callers to be okay with that case.

Another way to frame this is: is there a legitimate use case where someone is passing an `authPayload` to getAuthLevel, and they don't care about the document?

**Comment by chrismatix** [comment]
From a security heuristics' perspective we should add a special option that says 'I'm okay with that' aka treat empty authLevel as no auth level. Furthermore we should throw, if this option is not explicitly provided and there exists a getAuthLevel method.

This raises another question: Should we add a similar option like `allowUnauthorizedQueries` that is false by default? So, when a user calls `User.find()....` without either `authLevel` or `getAuthLevel`, the lib should throw by default.

**Comment by chrismatix** [comment]
Take a look at this https://www.owasp.org/index.php/Security_by_Design_Principles especially the section for secure defaults.

**Comment by makinde** [comment]
@xChrisPx Great link. Can you create a second issue for the second topic you brought up? It'll probably be really useful to have a clean place for each discussion.

To make sure you understand the specific issue here...the approach of providing a `getAuthLevel` function is not compatible with `Model.update` since `getAuthLevel` expect a document (which doesn't exist in memory for `Model.update`.  @brysgo's point is that he wants it to do option 1 below.

Here are the possible options:

1. throw an exception if you call `Model.update` and there's no `authLevel` passed in.
2. Let the call through, and force developers to write `getAuthLevel` to account for the case where `doc` is not passed in. This would allow people to have an `getAuthLevel` method that doesn't care about the doc (it may only care about the `authPayload`, which seems like a plausible case.
3. Add more configuration options for the developer to specify the behavior.

Of the options, (3) is probably the one I'd like to stay away from the most. Extra configurations add a lot of extra documentation and code complexity that must be maintained indefinitely. Simple API's are easier to learn and hopefully easier to maintain. In this case, it's not clear to me that there's a pressing, large need to add more configuration.

My 2c is that we go with something like (2). The way the code is written, if it can't find any authorization, the authorized field list is `[]`, and then the resulting code won't let you do anything since you don't have permissions to do anything. In that case, `Model.find()` will never return any objects and `Model.save()` will throw an exception if you changed anything.

To address the developer needing to handle an empty `doc`, that's legit. I think the best way to fix that  is to update line 11 of helpers.js to also include a check to make sure doc is truthy.

What do folks think about that?

**Comment by brysgo** [comment]
Hmm, I don't see the use case for wanting to write code that only has the `authPayload` in `getAuthLevel`. This is a function that lives in the model to assign a role that associates the user to the model. We have info about the user and none about the model, so the function cannot possibly do that task. The only thing I see it doing is causing confusion and bugs.

**Comment by makinde** [comment]
Yep. So I think you're agreeing with what I suggested, right?

> To address the developer needing to handle an empty doc, that's legit. I think the best way to fix that is to update line 11 of helpers.js to also include a check to make sure doc is truthy. If it isn't truthy, don't bother calling it. We should also probably only call it if there's an authPayload in the options as well.

**Comment by brysgo** [comment]
Hmm... sounds reasonable but not sufficient. If we want an option to call through anyways, I suggest we add another options like `documentContext` or something.

---
EDIT: I would love to see some additional options because I don't like jamming extra things in the auth payload.
`authPayload` - this is information about the current user accessing the resource
`authDocument` - (name up for debate) additional information about the document being accessed
`authResources` - (name up for debate) other things you could pass to the `getAuthLevel` function, this is useful if you need to consult external resources/documents to see if the user is authorized. In my case I am passing in dataloaders

**Comment by brysgo** [comment]
What I don't want is people wondering why updates are behaving differently than gets/saves.

**Comment by makinde** [comment]
There are perhaps two issues here.

1. What happens when the setup is supposed to use `getAuthLevel` but you attempt an update query. I think it's fine for getAuthFields to throw an error if you try to use it, there's a `getAuthLevel` method, but no doc. I think that's what you're looking for.

2. The authPayload is an arbitrary object.it isn't designed to be the user object. I pass in an object that looks roughly like `{ user: logginUser, organization: Foo }`. You should be able to put whatever info you need in there. The framework doesn't care, it just passes it along. The framework should know or care what the application needs to pass along.

**Comment by brysgo** [comment]
1. Exactly, that is what I am looking for.

2. I am also looking for the `authPayload` to be a bit more opinionated. I want it to explicitly be the information that the application needs to verify the user, it may not seem like the framework would need to care, but the mere presence of this information is of importance to the framework (deciding whether something is secure). Additionally, I think there is room for an arbitrary information field, but I think that presence of user authentication information and presence of extra relevant model information is important for the framework to know. For instance, in the case of (1) as you were saying, we would want to throw an error, except if the user is willing to provide that document information manually (explicitly that document information, and not implicitly through data that may or may not have been sent through the authPayload).

**Comment by makinde** [comment]
For number 2, I think there are use case beyond a user. What if someone's getAuthLevel wanted to check the last created book in the database, or if the authLevel depends on not the user, but the IP address.

The docs don't ever talk about users, but only about levels. I don't see a compelling reason to make things more specific. You can already accomplish the use cases you have with the existing, general API.

**Comment by brysgo** [comment]
@makinde - user/requestor/accessor call it what you like, it is the entity attempting the request

Choosing to ignore what is in the payload doesn't change the fact that this API is responsible for ensuring that some entity is only allowed to do the things they are authorized to do on a particular resource.

There will always be an entity accessing the resource, and there will always be a resource.

**Comment by brysgo** [comment]
My main concern is with ensuring that the user doesn't make mistakes that end up being fatal to the security of their program. By choosing to remain unaware of which of these concerns the user is providing information for, we are leaving ourselves less able to assist with ensuring such mistakes don't happen.

**Comment by makinde** [comment]
Interesting. What is the specific API you are suggesting this extension
expose to the developer?

**Comment by brysgo** [comment]
Just splitting `authPayload` into three variables that we still don't care about the specifics inside except to say that one represents information about the requester, one represents info about the resource, and the last represents miscellaneous data about the system that may be relevant.

What this helps us do is to say that, if an update is made where information about the resource is unavailable, the information that is provided about the requester is insufficient and an error is thrown.

If information is provided about the requester and about the resource being accessed, the update can call through to getAuthLevel with no problem.

The miscellaneous information option can be passed without affecting the decision on whether information is sufficient. For instance, if I have no info on the resource being accessed, my dataloaders will not help me that much. However, if I had just the id of the resource being accessed, I could use the dataloader to figure out the rest.

**Comment by makinde** [comment]
I see. And how does the developer pass these options to getAuthPayload? Is it 2 keys in the options to Model.find?

Perhaps a simple compromise it to make resolveAuthLevels throw an exception when there is a getAuthLevel method but doc or authPayload are missing. Then the developer can use a type system to enforce what data (mandatory or optional) is in that doc.

I'd prefer this as it keeps the interface simple. getAuthLevel will get two birds of data. First the context about who's acting, second is the resource being acted on. And it enforces that both are present.

**Comment by brysgo** [comment]
@makinde - it is not a compromise since that is exactly what I suggest :-)

We don't need to care what is in the doc, only that it is present, and the user can pass it in through the options (if they need to).

**Comment by makinde** [comment]
I'm not sure we are saying the same thing. Could you be more specific in the exact changes to code you are recommending? 

For clarity my suggestion is absolutely no change to the developer API or naming, and adding an except to be thrown if you provide a `getAuthMethod` function in your schema, and there is (no authLevel or authPaylod passed in the options) or there is no `doc` (Which would only happen for update queries).

I'm not suggesting that the developer can provide the doc themselves.

**Comment by brysgo** [comment]
@makinde - That last sentence is where our ideas diverge. Well, the second to last. I think that even if the authPayload is provided, if there is no doc, there should be an error. I think if the user wants to bypass the error, they need to explicitly pass a doc they wish to use instead.

This gets rid of implicit weirdness that someone who doesn't know about these quarks will experience when trying to do an update.

**Comment by makinde** [comment]
I've been on a phone See https://github.com/352Media/mongoose-authorization/pull/25

**Comment by makinde** [comment]
>  I think that even if the authPayload is provided, if there is no doc, there should be an error.

Yup, I agree.

> I think if the user wants to bypass the error, they need to explicitly pass a doc they wish to use instead.

I think adding this option only complicated the library and makes it harder to reason about how it'll work. With my proposal, if you want to update a doc and use `getAuthLevel`, you must load the document from memory and then use `Model.save()`. Limitations like this already exist. For instance, you cannot use `Model.create` because there's no place to pass options. you must create a new model and then call `.save()` on it.

The developer has to know about their weirdness in either case. In order to know that they need to pass in a doc when using `Model.update`, they'll need to realize that it doesn't get passed for them. I think it's just simpler to say, "Hey, use this other approach instead", which is often times how the mongoose library approach things. `Model.update` is known (or should be known) as a special case since validators and a few others things don't work with it.

**Comment by brysgo** [comment]
#25 addresses my concerns, I can't argue with your reasoning 👍
